// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package awsclient

import (
	"context"

	"github.com/Oleexo/jumphost-cli/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEC2 creates a new instance of MockEC2. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEC2(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEC2 {
	mock := &MockEC2{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEC2 is an autogenerated mock type for the EC2 type
type MockEC2 struct {
	mock.Mock
}

type MockEC2_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEC2) EXPECT() *MockEC2_Expecter {
	return &MockEC2_Expecter{mock: &_m.Mock}
}

// GetJumpHostInstance provides a mock function for the type MockEC2
func (_mock *MockEC2) GetJumpHostInstance(ctx context.Context, instanceID string) (models.JumphostInstance, error) {
	ret := _mock.Called(ctx, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for GetJumpHostInstance")
	}

	var r0 models.JumphostInstance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.JumphostInstance, error)); ok {
		return returnFunc(ctx, instanceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.JumphostInstance); ok {
		r0 = returnFunc(ctx, instanceID)
	} else {
		r0 = ret.Get(0).(models.JumphostInstance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, instanceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEC2_GetJumpHostInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJumpHostInstance'
type MockEC2_GetJumpHostInstance_Call struct {
	*mock.Call
}

// GetJumpHostInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID string
func (_e *MockEC2_Expecter) GetJumpHostInstance(ctx interface{}, instanceID interface{}) *MockEC2_GetJumpHostInstance_Call {
	return &MockEC2_GetJumpHostInstance_Call{Call: _e.mock.On("GetJumpHostInstance", ctx, instanceID)}
}

func (_c *MockEC2_GetJumpHostInstance_Call) Run(run func(ctx context.Context, instanceID string)) *MockEC2_GetJumpHostInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEC2_GetJumpHostInstance_Call) Return(jumphostInstance models.JumphostInstance, err error) *MockEC2_GetJumpHostInstance_Call {
	_c.Call.Return(jumphostInstance, err)
	return _c
}

func (_c *MockEC2_GetJumpHostInstance_Call) RunAndReturn(run func(ctx context.Context, instanceID string) (models.JumphostInstance, error)) *MockEC2_GetJumpHostInstance_Call {
	_c.Call.Return(run)
	return _c
}

// ListJumpHostInstances provides a mock function for the type MockEC2
func (_mock *MockEC2) ListJumpHostInstances(ctx context.Context, tagValue string) ([]models.JumphostInstance, error) {
	ret := _mock.Called(ctx, tagValue)

	if len(ret) == 0 {
		panic("no return value specified for ListJumpHostInstances")
	}

	var r0 []models.JumphostInstance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.JumphostInstance, error)); ok {
		return returnFunc(ctx, tagValue)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.JumphostInstance); ok {
		r0 = returnFunc(ctx, tagValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.JumphostInstance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tagValue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEC2_ListJumpHostInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJumpHostInstances'
type MockEC2_ListJumpHostInstances_Call struct {
	*mock.Call
}

// ListJumpHostInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - tagValue string
func (_e *MockEC2_Expecter) ListJumpHostInstances(ctx interface{}, tagValue interface{}) *MockEC2_ListJumpHostInstances_Call {
	return &MockEC2_ListJumpHostInstances_Call{Call: _e.mock.On("ListJumpHostInstances", ctx, tagValue)}
}

func (_c *MockEC2_ListJumpHostInstances_Call) Run(run func(ctx context.Context, tagValue string)) *MockEC2_ListJumpHostInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEC2_ListJumpHostInstances_Call) Return(jumphostInstances []models.JumphostInstance, err error) *MockEC2_ListJumpHostInstances_Call {
	_c.Call.Return(jumphostInstances, err)
	return _c
}

func (_c *MockEC2_ListJumpHostInstances_Call) RunAndReturn(run func(ctx context.Context, tagValue string) ([]models.JumphostInstance, error)) *MockEC2_ListJumpHostInstances_Call {
	_c.Call.Return(run)
	return _c
}
