// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package awsclient

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/eks"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEKSAPI creates a new instance of MockEKSAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEKSAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEKSAPI {
	mock := &MockEKSAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEKSAPI is an autogenerated mock type for the EKSAPI type
type MockEKSAPI struct {
	mock.Mock
}

type MockEKSAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEKSAPI) EXPECT() *MockEKSAPI_Expecter {
	return &MockEKSAPI_Expecter{mock: &_m.Mock}
}

// DescribeCluster provides a mock function for the type MockEKSAPI
func (_mock *MockEKSAPI) DescribeCluster(ctx context.Context, params *eks.DescribeClusterInput, optFns ...func(*eks.Options)) (*eks.DescribeClusterOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeCluster")
	}

	var r0 *eks.DescribeClusterOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *eks.DescribeClusterInput, ...func(*eks.Options)) (*eks.DescribeClusterOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *eks.DescribeClusterInput, ...func(*eks.Options)) *eks.DescribeClusterOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eks.DescribeClusterOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *eks.DescribeClusterInput, ...func(*eks.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEKSAPI_DescribeCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeCluster'
type MockEKSAPI_DescribeCluster_Call struct {
	*mock.Call
}

// DescribeCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - params *eks.DescribeClusterInput
//   - optFns ...func(*eks.Options)
func (_e *MockEKSAPI_Expecter) DescribeCluster(ctx interface{}, params interface{}, optFns ...interface{}) *MockEKSAPI_DescribeCluster_Call {
	return &MockEKSAPI_DescribeCluster_Call{Call: _e.mock.On("DescribeCluster",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockEKSAPI_DescribeCluster_Call) Run(run func(ctx context.Context, params *eks.DescribeClusterInput, optFns ...func(*eks.Options))) *MockEKSAPI_DescribeCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *eks.DescribeClusterInput
		if args[1] != nil {
			arg1 = args[1].(*eks.DescribeClusterInput)
		}
		var arg2 []func(*eks.Options)
		var variadicArgs []func(*eks.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*eks.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEKSAPI_DescribeCluster_Call) Return(describeClusterOutput *eks.DescribeClusterOutput, err error) *MockEKSAPI_DescribeCluster_Call {
	_c.Call.Return(describeClusterOutput, err)
	return _c
}

func (_c *MockEKSAPI_DescribeCluster_Call) RunAndReturn(run func(ctx context.Context, params *eks.DescribeClusterInput, optFns ...func(*eks.Options)) (*eks.DescribeClusterOutput, error)) *MockEKSAPI_DescribeCluster_Call {
	_c.Call.Return(run)
	return _c
}
