// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package awsclient

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/elasticache"
	mock "github.com/stretchr/testify/mock"
)

// NewMockElastiCacheAPI creates a new instance of MockElastiCacheAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockElastiCacheAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockElastiCacheAPI {
	mock := &MockElastiCacheAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockElastiCacheAPI is an autogenerated mock type for the ElastiCacheAPI type
type MockElastiCacheAPI struct {
	mock.Mock
}

type MockElastiCacheAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockElastiCacheAPI) EXPECT() *MockElastiCacheAPI_Expecter {
	return &MockElastiCacheAPI_Expecter{mock: &_m.Mock}
}

// DescribeCacheClusters provides a mock function for the type MockElastiCacheAPI
func (_mock *MockElastiCacheAPI) DescribeCacheClusters(ctx context.Context, params *elasticache.DescribeCacheClustersInput, optFns ...func(*elasticache.Options)) (*elasticache.DescribeCacheClustersOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeCacheClusters")
	}

	var r0 *elasticache.DescribeCacheClustersOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *elasticache.DescribeCacheClustersInput, ...func(*elasticache.Options)) (*elasticache.DescribeCacheClustersOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *elasticache.DescribeCacheClustersInput, ...func(*elasticache.Options)) *elasticache.DescribeCacheClustersOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elasticache.DescribeCacheClustersOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *elasticache.DescribeCacheClustersInput, ...func(*elasticache.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockElastiCacheAPI_DescribeCacheClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeCacheClusters'
type MockElastiCacheAPI_DescribeCacheClusters_Call struct {
	*mock.Call
}

// DescribeCacheClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - params *elasticache.DescribeCacheClustersInput
//   - optFns ...func(*elasticache.Options)
func (_e *MockElastiCacheAPI_Expecter) DescribeCacheClusters(ctx interface{}, params interface{}, optFns ...interface{}) *MockElastiCacheAPI_DescribeCacheClusters_Call {
	return &MockElastiCacheAPI_DescribeCacheClusters_Call{Call: _e.mock.On("DescribeCacheClusters",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockElastiCacheAPI_DescribeCacheClusters_Call) Run(run func(ctx context.Context, params *elasticache.DescribeCacheClustersInput, optFns ...func(*elasticache.Options))) *MockElastiCacheAPI_DescribeCacheClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *elasticache.DescribeCacheClustersInput
		if args[1] != nil {
			arg1 = args[1].(*elasticache.DescribeCacheClustersInput)
		}
		var arg2 []func(*elasticache.Options)
		var variadicArgs []func(*elasticache.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*elasticache.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockElastiCacheAPI_DescribeCacheClusters_Call) Return(describeCacheClustersOutput *elasticache.DescribeCacheClustersOutput, err error) *MockElastiCacheAPI_DescribeCacheClusters_Call {
	_c.Call.Return(describeCacheClustersOutput, err)
	return _c
}

func (_c *MockElastiCacheAPI_DescribeCacheClusters_Call) RunAndReturn(run func(ctx context.Context, params *elasticache.DescribeCacheClustersInput, optFns ...func(*elasticache.Options)) (*elasticache.DescribeCacheClustersOutput, error)) *MockElastiCacheAPI_DescribeCacheClusters_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeReplicationGroups provides a mock function for the type MockElastiCacheAPI
func (_mock *MockElastiCacheAPI) DescribeReplicationGroups(ctx context.Context, params *elasticache.DescribeReplicationGroupsInput, optFns ...func(*elasticache.Options)) (*elasticache.DescribeReplicationGroupsOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeReplicationGroups")
	}

	var r0 *elasticache.DescribeReplicationGroupsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *elasticache.DescribeReplicationGroupsInput, ...func(*elasticache.Options)) (*elasticache.DescribeReplicationGroupsOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *elasticache.DescribeReplicationGroupsInput, ...func(*elasticache.Options)) *elasticache.DescribeReplicationGroupsOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elasticache.DescribeReplicationGroupsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *elasticache.DescribeReplicationGroupsInput, ...func(*elasticache.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockElastiCacheAPI_DescribeReplicationGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeReplicationGroups'
type MockElastiCacheAPI_DescribeReplicationGroups_Call struct {
	*mock.Call
}

// DescribeReplicationGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - params *elasticache.DescribeReplicationGroupsInput
//   - optFns ...func(*elasticache.Options)
func (_e *MockElastiCacheAPI_Expecter) DescribeReplicationGroups(ctx interface{}, params interface{}, optFns ...interface{}) *MockElastiCacheAPI_DescribeReplicationGroups_Call {
	return &MockElastiCacheAPI_DescribeReplicationGroups_Call{Call: _e.mock.On("DescribeReplicationGroups",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockElastiCacheAPI_DescribeReplicationGroups_Call) Run(run func(ctx context.Context, params *elasticache.DescribeReplicationGroupsInput, optFns ...func(*elasticache.Options))) *MockElastiCacheAPI_DescribeReplicationGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *elasticache.DescribeReplicationGroupsInput
		if args[1] != nil {
			arg1 = args[1].(*elasticache.DescribeReplicationGroupsInput)
		}
		var arg2 []func(*elasticache.Options)
		var variadicArgs []func(*elasticache.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*elasticache.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockElastiCacheAPI_DescribeReplicationGroups_Call) Return(describeReplicationGroupsOutput *elasticache.DescribeReplicationGroupsOutput, err error) *MockElastiCacheAPI_DescribeReplicationGroups_Call {
	_c.Call.Return(describeReplicationGroupsOutput, err)
	return _c
}

func (_c *MockElastiCacheAPI_DescribeReplicationGroups_Call) RunAndReturn(run func(ctx context.Context, params *elasticache.DescribeReplicationGroupsInput, optFns ...func(*elasticache.Options)) (*elasticache.DescribeReplicationGroupsOutput, error)) *MockElastiCacheAPI_DescribeReplicationGroups_Call {
	_c.Call.Return(run)
	return _c
}
