// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package awsclient

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIdentity creates a new instance of MockIdentity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentity(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentity {
	mock := &MockIdentity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdentity is an autogenerated mock type for the Identity type
type MockIdentity struct {
	mock.Mock
}

type MockIdentity_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentity) EXPECT() *MockIdentity_Expecter {
	return &MockIdentity_Expecter{mock: &_m.Mock}
}

// Account provides a mock function for the type MockIdentity
func (_mock *MockIdentity) Account() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Account")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIdentity_Account_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Account'
type MockIdentity_Account_Call struct {
	*mock.Call
}

// Account is a helper method to define mock.On call
func (_e *MockIdentity_Expecter) Account() *MockIdentity_Account_Call {
	return &MockIdentity_Account_Call{Call: _e.mock.On("Account")}
}

func (_c *MockIdentity_Account_Call) Run(run func()) *MockIdentity_Account_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIdentity_Account_Call) Return(s string) *MockIdentity_Account_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIdentity_Account_Call) RunAndReturn(run func() string) *MockIdentity_Account_Call {
	_c.Call.Return(run)
	return _c
}

// Arn provides a mock function for the type MockIdentity
func (_mock *MockIdentity) Arn() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Arn")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIdentity_Arn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Arn'
type MockIdentity_Arn_Call struct {
	*mock.Call
}

// Arn is a helper method to define mock.On call
func (_e *MockIdentity_Expecter) Arn() *MockIdentity_Arn_Call {
	return &MockIdentity_Arn_Call{Call: _e.mock.On("Arn")}
}

func (_c *MockIdentity_Arn_Call) Run(run func()) *MockIdentity_Arn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIdentity_Arn_Call) Return(s string) *MockIdentity_Arn_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIdentity_Arn_Call) RunAndReturn(run func() string) *MockIdentity_Arn_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockIdentity
func (_mock *MockIdentity) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIdentity_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockIdentity_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockIdentity_Expecter) String() *MockIdentity_String_Call {
	return &MockIdentity_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockIdentity_String_Call) Run(run func()) *MockIdentity_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIdentity_String_Call) Return(s string) *MockIdentity_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIdentity_String_Call) RunAndReturn(run func() string) *MockIdentity_String_Call {
	_c.Call.Return(run)
	return _c
}

// UserID provides a mock function for the type MockIdentity
func (_mock *MockIdentity) UserID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIdentity_UserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserID'
type MockIdentity_UserID_Call struct {
	*mock.Call
}

// UserID is a helper method to define mock.On call
func (_e *MockIdentity_Expecter) UserID() *MockIdentity_UserID_Call {
	return &MockIdentity_UserID_Call{Call: _e.mock.On("UserID")}
}

func (_c *MockIdentity_UserID_Call) Run(run func()) *MockIdentity_UserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIdentity_UserID_Call) Return(s string) *MockIdentity_UserID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIdentity_UserID_Call) RunAndReturn(run func() string) *MockIdentity_UserID_Call {
	_c.Call.Return(run)
	return _c
}
