// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package awsclient

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/opensearch"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOpenSearchAPI creates a new instance of MockOpenSearchAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpenSearchAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpenSearchAPI {
	mock := &MockOpenSearchAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOpenSearchAPI is an autogenerated mock type for the OpenSearchAPI type
type MockOpenSearchAPI struct {
	mock.Mock
}

type MockOpenSearchAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpenSearchAPI) EXPECT() *MockOpenSearchAPI_Expecter {
	return &MockOpenSearchAPI_Expecter{mock: &_m.Mock}
}

// DescribeDomain provides a mock function for the type MockOpenSearchAPI
func (_mock *MockOpenSearchAPI) DescribeDomain(ctx context.Context, params *opensearch.DescribeDomainInput, optFns ...func(*opensearch.Options)) (*opensearch.DescribeDomainOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeDomain")
	}

	var r0 *opensearch.DescribeDomainOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.DescribeDomainInput, ...func(*opensearch.Options)) (*opensearch.DescribeDomainOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.DescribeDomainInput, ...func(*opensearch.Options)) *opensearch.DescribeDomainOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opensearch.DescribeDomainOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opensearch.DescribeDomainInput, ...func(*opensearch.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOpenSearchAPI_DescribeDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeDomain'
type MockOpenSearchAPI_DescribeDomain_Call struct {
	*mock.Call
}

// DescribeDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - params *opensearch.DescribeDomainInput
//   - optFns ...func(*opensearch.Options)
func (_e *MockOpenSearchAPI_Expecter) DescribeDomain(ctx interface{}, params interface{}, optFns ...interface{}) *MockOpenSearchAPI_DescribeDomain_Call {
	return &MockOpenSearchAPI_DescribeDomain_Call{Call: _e.mock.On("DescribeDomain",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockOpenSearchAPI_DescribeDomain_Call) Run(run func(ctx context.Context, params *opensearch.DescribeDomainInput, optFns ...func(*opensearch.Options))) *MockOpenSearchAPI_DescribeDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opensearch.DescribeDomainInput
		if args[1] != nil {
			arg1 = args[1].(*opensearch.DescribeDomainInput)
		}
		var arg2 []func(*opensearch.Options)
		var variadicArgs []func(*opensearch.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*opensearch.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockOpenSearchAPI_DescribeDomain_Call) Return(describeDomainOutput *opensearch.DescribeDomainOutput, err error) *MockOpenSearchAPI_DescribeDomain_Call {
	_c.Call.Return(describeDomainOutput, err)
	return _c
}

func (_c *MockOpenSearchAPI_DescribeDomain_Call) RunAndReturn(run func(ctx context.Context, params *opensearch.DescribeDomainInput, optFns ...func(*opensearch.Options)) (*opensearch.DescribeDomainOutput, error)) *MockOpenSearchAPI_DescribeDomain_Call {
	_c.Call.Return(run)
	return _c
}

// ListDomainNames provides a mock function for the type MockOpenSearchAPI
func (_mock *MockOpenSearchAPI) ListDomainNames(ctx context.Context, params *opensearch.ListDomainNamesInput, optFns ...func(*opensearch.Options)) (*opensearch.ListDomainNamesOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListDomainNames")
	}

	var r0 *opensearch.ListDomainNamesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.ListDomainNamesInput, ...func(*opensearch.Options)) (*opensearch.ListDomainNamesOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.ListDomainNamesInput, ...func(*opensearch.Options)) *opensearch.ListDomainNamesOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opensearch.ListDomainNamesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opensearch.ListDomainNamesInput, ...func(*opensearch.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOpenSearchAPI_ListDomainNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDomainNames'
type MockOpenSearchAPI_ListDomainNames_Call struct {
	*mock.Call
}

// ListDomainNames is a helper method to define mock.On call
//   - ctx context.Context
//   - params *opensearch.ListDomainNamesInput
//   - optFns ...func(*opensearch.Options)
func (_e *MockOpenSearchAPI_Expecter) ListDomainNames(ctx interface{}, params interface{}, optFns ...interface{}) *MockOpenSearchAPI_ListDomainNames_Call {
	return &MockOpenSearchAPI_ListDomainNames_Call{Call: _e.mock.On("ListDomainNames",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockOpenSearchAPI_ListDomainNames_Call) Run(run func(ctx context.Context, params *opensearch.ListDomainNamesInput, optFns ...func(*opensearch.Options))) *MockOpenSearchAPI_ListDomainNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opensearch.ListDomainNamesInput
		if args[1] != nil {
			arg1 = args[1].(*opensearch.ListDomainNamesInput)
		}
		var arg2 []func(*opensearch.Options)
		var variadicArgs []func(*opensearch.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*opensearch.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockOpenSearchAPI_ListDomainNames_Call) Return(listDomainNamesOutput *opensearch.ListDomainNamesOutput, err error) *MockOpenSearchAPI_ListDomainNames_Call {
	_c.Call.Return(listDomainNamesOutput, err)
	return _c
}

func (_c *MockOpenSearchAPI_ListDomainNames_Call) RunAndReturn(run func(ctx context.Context, params *opensearch.ListDomainNamesInput, optFns ...func(*opensearch.Options)) (*opensearch.ListDomainNamesOutput, error)) *MockOpenSearchAPI_ListDomainNames_Call {
	_c.Call.Return(run)
	return _c
}
