// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package awsclient

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/rds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRDSAPI creates a new instance of MockRDSAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRDSAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRDSAPI {
	mock := &MockRDSAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRDSAPI is an autogenerated mock type for the RDSAPI type
type MockRDSAPI struct {
	mock.Mock
}

type MockRDSAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRDSAPI) EXPECT() *MockRDSAPI_Expecter {
	return &MockRDSAPI_Expecter{mock: &_m.Mock}
}

// DescribeDBInstances provides a mock function for the type MockRDSAPI
func (_mock *MockRDSAPI) DescribeDBInstances(ctx context.Context, params *rds.DescribeDBInstancesInput, optFns ...func(*rds.Options)) (*rds.DescribeDBInstancesOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeDBInstances")
	}

	var r0 *rds.DescribeDBInstancesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.DescribeDBInstancesInput, ...func(*rds.Options)) (*rds.DescribeDBInstancesOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.DescribeDBInstancesInput, ...func(*rds.Options)) *rds.DescribeDBInstancesOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rds.DescribeDBInstancesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *rds.DescribeDBInstancesInput, ...func(*rds.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRDSAPI_DescribeDBInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeDBInstances'
type MockRDSAPI_DescribeDBInstances_Call struct {
	*mock.Call
}

// DescribeDBInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - params *rds.DescribeDBInstancesInput
//   - optFns ...func(*rds.Options)
func (_e *MockRDSAPI_Expecter) DescribeDBInstances(ctx interface{}, params interface{}, optFns ...interface{}) *MockRDSAPI_DescribeDBInstances_Call {
	return &MockRDSAPI_DescribeDBInstances_Call{Call: _e.mock.On("DescribeDBInstances",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockRDSAPI_DescribeDBInstances_Call) Run(run func(ctx context.Context, params *rds.DescribeDBInstancesInput, optFns ...func(*rds.Options))) *MockRDSAPI_DescribeDBInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *rds.DescribeDBInstancesInput
		if args[1] != nil {
			arg1 = args[1].(*rds.DescribeDBInstancesInput)
		}
		var arg2 []func(*rds.Options)
		var variadicArgs []func(*rds.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*rds.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRDSAPI_DescribeDBInstances_Call) Return(describeDBInstancesOutput *rds.DescribeDBInstancesOutput, err error) *MockRDSAPI_DescribeDBInstances_Call {
	_c.Call.Return(describeDBInstancesOutput, err)
	return _c
}

func (_c *MockRDSAPI_DescribeDBInstances_Call) RunAndReturn(run func(ctx context.Context, params *rds.DescribeDBInstancesInput, optFns ...func(*rds.Options)) (*rds.DescribeDBInstancesOutput, error)) *MockRDSAPI_DescribeDBInstances_Call {
	_c.Call.Return(run)
	return _c
}
