// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package awsclient

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/redshift"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRedshiftAPI creates a new instance of MockRedshiftAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedshiftAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedshiftAPI {
	mock := &MockRedshiftAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedshiftAPI is an autogenerated mock type for the RedshiftAPI type
type MockRedshiftAPI struct {
	mock.Mock
}

type MockRedshiftAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedshiftAPI) EXPECT() *MockRedshiftAPI_Expecter {
	return &MockRedshiftAPI_Expecter{mock: &_m.Mock}
}

// DescribeClusters provides a mock function for the type MockRedshiftAPI
func (_mock *MockRedshiftAPI) DescribeClusters(ctx context.Context, params *redshift.DescribeClustersInput, optFns ...func(*redshift.Options)) (*redshift.DescribeClustersOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeClusters")
	}

	var r0 *redshift.DescribeClustersOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *redshift.DescribeClustersInput, ...func(*redshift.Options)) (*redshift.DescribeClustersOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *redshift.DescribeClustersInput, ...func(*redshift.Options)) *redshift.DescribeClustersOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redshift.DescribeClustersOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *redshift.DescribeClustersInput, ...func(*redshift.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRedshiftAPI_DescribeClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeClusters'
type MockRedshiftAPI_DescribeClusters_Call struct {
	*mock.Call
}

// DescribeClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - params *redshift.DescribeClustersInput
//   - optFns ...func(*redshift.Options)
func (_e *MockRedshiftAPI_Expecter) DescribeClusters(ctx interface{}, params interface{}, optFns ...interface{}) *MockRedshiftAPI_DescribeClusters_Call {
	return &MockRedshiftAPI_DescribeClusters_Call{Call: _e.mock.On("DescribeClusters",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockRedshiftAPI_DescribeClusters_Call) Run(run func(ctx context.Context, params *redshift.DescribeClustersInput, optFns ...func(*redshift.Options))) *MockRedshiftAPI_DescribeClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *redshift.DescribeClustersInput
		if args[1] != nil {
			arg1 = args[1].(*redshift.DescribeClustersInput)
		}
		var arg2 []func(*redshift.Options)
		var variadicArgs []func(*redshift.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*redshift.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRedshiftAPI_DescribeClusters_Call) Return(describeClustersOutput *redshift.DescribeClustersOutput, err error) *MockRedshiftAPI_DescribeClusters_Call {
	_c.Call.Return(describeClustersOutput, err)
	return _c
}

func (_c *MockRedshiftAPI_DescribeClusters_Call) RunAndReturn(run func(ctx context.Context, params *redshift.DescribeClustersInput, optFns ...func(*redshift.Options)) (*redshift.DescribeClustersOutput, error)) *MockRedshiftAPI_DescribeClusters_Call {
	_c.Call.Return(run)
	return _c
}
