// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ui

import (
	"github.com/Oleexo/jumphost-cli/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDisplay creates a new instance of MockDisplay. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDisplay(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDisplay {
	mock := &MockDisplay{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDisplay is an autogenerated mock type for the Display type
type MockDisplay struct {
	mock.Mock
}

type MockDisplay_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDisplay) EXPECT() *MockDisplay_Expecter {
	return &MockDisplay_Expecter{mock: &_m.Mock}
}

// Loading provides a mock function for the type MockDisplay
func (_mock *MockDisplay) Loading(message string, loader func() (any, error)) (any, error) {
	ret := _mock.Called(message, loader)

	if len(ret) == 0 {
		panic("no return value specified for Loading")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, func() (any, error)) (any, error)); ok {
		return returnFunc(message, loader)
	}
	if returnFunc, ok := ret.Get(0).(func(string, func() (any, error)) any); ok {
		r0 = returnFunc(message, loader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, func() (any, error)) error); ok {
		r1 = returnFunc(message, loader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDisplay_Loading_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Loading'
type MockDisplay_Loading_Call struct {
	*mock.Call
}

// Loading is a helper method to define mock.On call
//   - message string
//   - loader func() (any, error)
func (_e *MockDisplay_Expecter) Loading(message interface{}, loader interface{}) *MockDisplay_Loading_Call {
	return &MockDisplay_Loading_Call{Call: _e.mock.On("Loading", message, loader)}
}

func (_c *MockDisplay_Loading_Call) Run(run func(message string, loader func() (any, error))) *MockDisplay_Loading_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func() (any, error)
		if args[1] != nil {
			arg1 = args[1].(func() (any, error))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDisplay_Loading_Call) Return(v any, err error) *MockDisplay_Loading_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDisplay_Loading_Call) RunAndReturn(run func(message string, loader func() (any, error)) (any, error)) *MockDisplay_Loading_Call {
	_c.Call.Return(run)
	return _c
}

// Print provides a mock function for the type MockDisplay
func (_mock *MockDisplay) Print(message string) {
	_mock.Called(message)
	return
}

// MockDisplay_Print_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Print'
type MockDisplay_Print_Call struct {
	*mock.Call
}

// Print is a helper method to define mock.On call
//   - message string
func (_e *MockDisplay_Expecter) Print(message interface{}) *MockDisplay_Print_Call {
	return &MockDisplay_Print_Call{Call: _e.mock.On("Print", message)}
}

func (_c *MockDisplay_Print_Call) Run(run func(message string)) *MockDisplay_Print_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDisplay_Print_Call) Return() *MockDisplay_Print_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDisplay_Print_Call) RunAndReturn(run func(message string)) *MockDisplay_Print_Call {
	_c.Run(run)
	return _c
}

// PrintError provides a mock function for the type MockDisplay
func (_mock *MockDisplay) PrintError(message string, err error) {
	_mock.Called(message, err)
	return
}

// MockDisplay_PrintError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrintError'
type MockDisplay_PrintError_Call struct {
	*mock.Call
}

// PrintError is a helper method to define mock.On call
//   - message string
//   - err error
func (_e *MockDisplay_Expecter) PrintError(message interface{}, err interface{}) *MockDisplay_PrintError_Call {
	return &MockDisplay_PrintError_Call{Call: _e.mock.On("PrintError", message, err)}
}

func (_c *MockDisplay_PrintError_Call) Run(run func(message string, err error)) *MockDisplay_PrintError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDisplay_PrintError_Call) Return() *MockDisplay_PrintError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDisplay_PrintError_Call) RunAndReturn(run func(message string, err error)) *MockDisplay_PrintError_Call {
	_c.Run(run)
	return _c
}

// PrintErrorf provides a mock function for the type MockDisplay
func (_mock *MockDisplay) PrintErrorf(format string, a ...any) {
	if len(a) > 0 {
		_mock.Called(format, a)
	} else {
		_mock.Called(format)
	}

	return
}

// MockDisplay_PrintErrorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrintErrorf'
type MockDisplay_PrintErrorf_Call struct {
	*mock.Call
}

// PrintErrorf is a helper method to define mock.On call
//   - format string
//   - a ...any
func (_e *MockDisplay_Expecter) PrintErrorf(format interface{}, a ...interface{}) *MockDisplay_PrintErrorf_Call {
	return &MockDisplay_PrintErrorf_Call{Call: _e.mock.On("PrintErrorf",
		append([]interface{}{format}, a...)...)}
}

func (_c *MockDisplay_PrintErrorf_Call) Run(run func(format string, a ...any)) *MockDisplay_PrintErrorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockDisplay_PrintErrorf_Call) Return() *MockDisplay_PrintErrorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDisplay_PrintErrorf_Call) RunAndReturn(run func(format string, a ...any)) *MockDisplay_PrintErrorf_Call {
	_c.Run(run)
	return _c
}

// SelectJumphostInstance provides a mock function for the type MockDisplay
func (_mock *MockDisplay) SelectJumphostInstance(fn func() ([]models.JumphostInstance, error)) (models.JumphostInstance, bool, error) {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for SelectJumphostInstance")
	}

	var r0 models.JumphostInstance
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(func() ([]models.JumphostInstance, error)) (models.JumphostInstance, bool, error)); ok {
		return returnFunc(fn)
	}
	if returnFunc, ok := ret.Get(0).(func(func() ([]models.JumphostInstance, error)) models.JumphostInstance); ok {
		r0 = returnFunc(fn)
	} else {
		r0 = ret.Get(0).(models.JumphostInstance)
	}
	if returnFunc, ok := ret.Get(1).(func(func() ([]models.JumphostInstance, error)) bool); ok {
		r1 = returnFunc(fn)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(func() ([]models.JumphostInstance, error)) error); ok {
		r2 = returnFunc(fn)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDisplay_SelectJumphostInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectJumphostInstance'
type MockDisplay_SelectJumphostInstance_Call struct {
	*mock.Call
}

// SelectJumphostInstance is a helper method to define mock.On call
//   - fn func() ([]models.JumphostInstance, error)
func (_e *MockDisplay_Expecter) SelectJumphostInstance(fn interface{}) *MockDisplay_SelectJumphostInstance_Call {
	return &MockDisplay_SelectJumphostInstance_Call{Call: _e.mock.On("SelectJumphostInstance", fn)}
}

func (_c *MockDisplay_SelectJumphostInstance_Call) Run(run func(fn func() ([]models.JumphostInstance, error))) *MockDisplay_SelectJumphostInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func() ([]models.JumphostInstance, error)
		if args[0] != nil {
			arg0 = args[0].(func() ([]models.JumphostInstance, error))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDisplay_SelectJumphostInstance_Call) Return(jumphostInstance models.JumphostInstance, b bool, err error) *MockDisplay_SelectJumphostInstance_Call {
	_c.Call.Return(jumphostInstance, b, err)
	return _c
}

func (_c *MockDisplay_SelectJumphostInstance_Call) RunAndReturn(run func(fn func() ([]models.JumphostInstance, error)) (models.JumphostInstance, bool, error)) *MockDisplay_SelectJumphostInstance_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLocalPort provides a mock function for the type MockDisplay
func (_mock *MockDisplay) SelectLocalPort(port int) int {
	ret := _mock.Called(port)

	if len(ret) == 0 {
		panic("no return value specified for SelectLocalPort")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(int) int); ok {
		r0 = returnFunc(port)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockDisplay_SelectLocalPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLocalPort'
type MockDisplay_SelectLocalPort_Call struct {
	*mock.Call
}

// SelectLocalPort is a helper method to define mock.On call
//   - port int
func (_e *MockDisplay_Expecter) SelectLocalPort(port interface{}) *MockDisplay_SelectLocalPort_Call {
	return &MockDisplay_SelectLocalPort_Call{Call: _e.mock.On("SelectLocalPort", port)}
}

func (_c *MockDisplay_SelectLocalPort_Call) Run(run func(port int)) *MockDisplay_SelectLocalPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDisplay_SelectLocalPort_Call) Return(n int) *MockDisplay_SelectLocalPort_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockDisplay_SelectLocalPort_Call) RunAndReturn(run func(port int) int) *MockDisplay_SelectLocalPort_Call {
	_c.Call.Return(run)
	return _c
}

// SelectRegion provides a mock function for the type MockDisplay
func (_mock *MockDisplay) SelectRegion(regions []models.Region) models.Region {
	ret := _mock.Called(regions)

	if len(ret) == 0 {
		panic("no return value specified for SelectRegion")
	}

	var r0 models.Region
	if returnFunc, ok := ret.Get(0).(func([]models.Region) models.Region); ok {
		r0 = returnFunc(regions)
	} else {
		r0 = ret.Get(0).(models.Region)
	}
	return r0
}

// MockDisplay_SelectRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectRegion'
type MockDisplay_SelectRegion_Call struct {
	*mock.Call
}

// SelectRegion is a helper method to define mock.On call
//   - regions []models.Region
func (_e *MockDisplay_Expecter) SelectRegion(regions interface{}) *MockDisplay_SelectRegion_Call {
	return &MockDisplay_SelectRegion_Call{Call: _e.mock.On("SelectRegion", regions)}
}

func (_c *MockDisplay_SelectRegion_Call) Run(run func(regions []models.Region)) *MockDisplay_SelectRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.Region
		if args[0] != nil {
			arg0 = args[0].([]models.Region)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDisplay_SelectRegion_Call) Return(region models.Region) *MockDisplay_SelectRegion_Call {
	_c.Call.Return(region)
	return _c
}

func (_c *MockDisplay_SelectRegion_Call) RunAndReturn(run func(regions []models.Region) models.Region) *MockDisplay_SelectRegion_Call {
	_c.Call.Return(run)
	return _c
}

// SelectService provides a mock function for the type MockDisplay
func (_mock *MockDisplay) SelectService(services []models.Service) (models.Service, bool) {
	ret := _mock.Called(services)

	if len(ret) == 0 {
		panic("no return value specified for SelectService")
	}

	var r0 models.Service
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func([]models.Service) (models.Service, bool)); ok {
		return returnFunc(services)
	}
	if returnFunc, ok := ret.Get(0).(func([]models.Service) models.Service); ok {
		r0 = returnFunc(services)
	} else {
		r0 = ret.Get(0).(models.Service)
	}
	if returnFunc, ok := ret.Get(1).(func([]models.Service) bool); ok {
		r1 = returnFunc(services)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockDisplay_SelectService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectService'
type MockDisplay_SelectService_Call struct {
	*mock.Call
}

// SelectService is a helper method to define mock.On call
//   - services []models.Service
func (_e *MockDisplay_Expecter) SelectService(services interface{}) *MockDisplay_SelectService_Call {
	return &MockDisplay_SelectService_Call{Call: _e.mock.On("SelectService", services)}
}

func (_c *MockDisplay_SelectService_Call) Run(run func(services []models.Service)) *MockDisplay_SelectService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.Service
		if args[0] != nil {
			arg0 = args[0].([]models.Service)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDisplay_SelectService_Call) Return(service models.Service, b bool) *MockDisplay_SelectService_Call {
	_c.Call.Return(service, b)
	return _c
}

func (_c *MockDisplay_SelectService_Call) RunAndReturn(run func(services []models.Service) (models.Service, bool)) *MockDisplay_SelectService_Call {
	_c.Call.Return(run)
	return _c
}

// SelectTarget provides a mock function for the type MockDisplay
func (_mock *MockDisplay) SelectTarget(service models.Service, loader func() ([]models.ConnectionParams, error)) (models.ConnectionParams, bool) {
	ret := _mock.Called(service, loader)

	if len(ret) == 0 {
		panic("no return value specified for SelectTarget")
	}

	var r0 models.ConnectionParams
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(models.Service, func() ([]models.ConnectionParams, error)) (models.ConnectionParams, bool)); ok {
		return returnFunc(service, loader)
	}
	if returnFunc, ok := ret.Get(0).(func(models.Service, func() ([]models.ConnectionParams, error)) models.ConnectionParams); ok {
		r0 = returnFunc(service, loader)
	} else {
		r0 = ret.Get(0).(models.ConnectionParams)
	}
	if returnFunc, ok := ret.Get(1).(func(models.Service, func() ([]models.ConnectionParams, error)) bool); ok {
		r1 = returnFunc(service, loader)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockDisplay_SelectTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectTarget'
type MockDisplay_SelectTarget_Call struct {
	*mock.Call
}

// SelectTarget is a helper method to define mock.On call
//   - service models.Service
//   - loader func() ([]models.ConnectionParams, error)
func (_e *MockDisplay_Expecter) SelectTarget(service interface{}, loader interface{}) *MockDisplay_SelectTarget_Call {
	return &MockDisplay_SelectTarget_Call{Call: _e.mock.On("SelectTarget", service, loader)}
}

func (_c *MockDisplay_SelectTarget_Call) Run(run func(service models.Service, loader func() ([]models.ConnectionParams, error))) *MockDisplay_SelectTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.Service
		if args[0] != nil {
			arg0 = args[0].(models.Service)
		}
		var arg1 func() ([]models.ConnectionParams, error)
		if args[1] != nil {
			arg1 = args[1].(func() ([]models.ConnectionParams, error))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDisplay_SelectTarget_Call) Return(connectionParams models.ConnectionParams, b bool) *MockDisplay_SelectTarget_Call {
	_c.Call.Return(connectionParams, b)
	return _c
}

func (_c *MockDisplay_SelectTarget_Call) RunAndReturn(run func(service models.Service, loader func() ([]models.ConnectionParams, error)) (models.ConnectionParams, bool)) *MockDisplay_SelectTarget_Call {
	_c.Call.Return(run)
	return _c
}

// SetIdentity provides a mock function for the type MockDisplay
func (_mock *MockDisplay) SetIdentity(identity Identity) {
	_mock.Called(identity)
	return
}

// MockDisplay_SetIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIdentity'
type MockDisplay_SetIdentity_Call struct {
	*mock.Call
}

// SetIdentity is a helper method to define mock.On call
//   - identity Identity
func (_e *MockDisplay_Expecter) SetIdentity(identity interface{}) *MockDisplay_SetIdentity_Call {
	return &MockDisplay_SetIdentity_Call{Call: _e.mock.On("SetIdentity", identity)}
}

func (_c *MockDisplay_SetIdentity_Call) Run(run func(identity Identity)) *MockDisplay_SetIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Identity
		if args[0] != nil {
			arg0 = args[0].(Identity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDisplay_SetIdentity_Call) Return() *MockDisplay_SetIdentity_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDisplay_SetIdentity_Call) RunAndReturn(run func(identity Identity)) *MockDisplay_SetIdentity_Call {
	_c.Run(run)
	return _c
}

// StartJumphost provides a mock function for the type MockDisplay
func (_mock *MockDisplay) StartJumphost(jumphost models.JumphostInstance, info models.ConnectionParams) error {
	ret := _mock.Called(jumphost, info)

	if len(ret) == 0 {
		panic("no return value specified for StartJumphost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.JumphostInstance, models.ConnectionParams) error); ok {
		r0 = returnFunc(jumphost, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDisplay_StartJumphost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartJumphost'
type MockDisplay_StartJumphost_Call struct {
	*mock.Call
}

// StartJumphost is a helper method to define mock.On call
//   - jumphost models.JumphostInstance
//   - info models.ConnectionParams
func (_e *MockDisplay_Expecter) StartJumphost(jumphost interface{}, info interface{}) *MockDisplay_StartJumphost_Call {
	return &MockDisplay_StartJumphost_Call{Call: _e.mock.On("StartJumphost", jumphost, info)}
}

func (_c *MockDisplay_StartJumphost_Call) Run(run func(jumphost models.JumphostInstance, info models.ConnectionParams)) *MockDisplay_StartJumphost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.JumphostInstance
		if args[0] != nil {
			arg0 = args[0].(models.JumphostInstance)
		}
		var arg1 models.ConnectionParams
		if args[1] != nil {
			arg1 = args[1].(models.ConnectionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDisplay_StartJumphost_Call) Return(err error) *MockDisplay_StartJumphost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDisplay_StartJumphost_Call) RunAndReturn(run func(jumphost models.JumphostInstance, info models.ConnectionParams) error) *MockDisplay_StartJumphost_Call {
	_c.Call.Return(run)
	return _c
}
